export const CHANGE_ADD_FORM = 'CHANGE_ADD_FORM';
export const MAIN_OPEN_GROUP_LIST = 'MAIN_OPEN_GROUP_LIST';
export const CHANGE_SIDEBAR_STATUS = 'CHANGE_SIDEBAR_STATUS';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const OPEN_GROUP_ADD_FROM = 'OPEN_GROUP_ADD_FROM';