import * as types from '../actions/ActionTypes';

const initialState = {
  contact:{
    group:[
    {
      title:"가족",
      admin:true
    },
    {
      title:"친구",
      admin:true
    },
    {
      title:"회사",
      admin:false
    },
    {
      title:"자연친구들",
      admin:true
    }
    ],
    list:[
    [
      {
        name:"ㅇㅇㅇ",
        category:"아버지",
        phone:"010-1234-4567",
        business_call:"02-1234-4567",
        business:"없음",
        email:"userid@gmail.com",
        address:"집",
        profile_iamge:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwTRkf2JdOw1pAZTMImAv3eEIQr0QDVGL_H0hzxiR3PiBk9SASjg",
        access:true
      },
      {
        name:"ㄴㄴㄴ",
        category:"어머니",
        phone:"010-1234-4567",
        business_call:"02-1234-4567",
        business:"없음",
        email:"nyaa@gmail.com",
        address:"집",
        profile_iamge:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwTRkf2JdOw1pAZTMImAv3eEIQr0QDVGL_H0hzxiR3PiBk9SASjg",
        access:true
      },
      {
        name:"ㄷㄷㄷ",
        category:"큰동생",
        phone:"010-1234-4567",
        business_call:"02-1234-4567",
        business:"없음",
        email:"userid@gmail.com",
        address:"집",
        profile_iamge:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwTRkf2JdOw1pAZTMImAv3eEIQr0QDVGL_H0hzxiR3PiBk9SASjg",
        access:true
      },
      {
        name:"ㄹㄹㄹ",
        category:"작은동생",
        phone:"010-1234-4567",
        business_call:"02-1234-4567",
        business:"없음",
        email:"userid@gmail.com",
        address:"집",
        profile_iamge:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwTRkf2JdOw1pAZTMImAv3eEIQr0QDVGL_H0hzxiR3PiBk9SASjg",
        access:true
      },
    ],
    [
      {
        name:"ㅗㅜㅑ",
        category:"친구",
        phone:"010-1234-4567",
        business_call:"02-1234-4567",
        business:"없음",
        email:"nyaa@gmail.com",
        address:"어딘가",
        profile_iamge:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwTRkf2JdOw1pAZTMImAv3eEIQr0QDVGL_H0hzxiR3PiBk9SASjg",
        access:false
      },
      {
        name:"ㅏㅢㅏㅏ",
        category:"친구",
        phone:"010-1234-4567",
        business_call:"02-1234-4567",
        business:"없음",
        email:"nyaa@gmail.com",
        address:"어딘가",
        profile_iamge:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwTRkf2JdOw1pAZTMImAv3eEIQr0QDVGL_H0hzxiR3PiBk9SASjg",
        access:false
      },
      {
        name:"음음음",
        category:"친구",
        phone:"010-1234-4567",
        business_call:"02-1234-4567",
        business:"없음",
        email:"nyaa@gmail.com",
        address:"어딘가",
        profile_iamge:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwTRkf2JdOw1pAZTMImAv3eEIQr0QDVGL_H0hzxiR3PiBk9SASjg",
        access:false
      }
    ],
    [
      {
        name:"홍석",
        category:"음냐",
        phone:"010-1234-4567",
        business_call:"02-1234-4567",
        business:"퍄퍄",
        email:"이메일@이메일.com",
        address:"서울어딘가",
        profile_iamge:"http://thesocialmediamonthly.com/wp-content/uploads/2015/08/photo.png",
        access:false
      },
      {
        name:"홍길동",
        category:"가족",
        phone:"010-1234-4567",
        business_call:"02-1234-4567",
        business:"큰 회사",
        email:"이메일@이메일.com",
        address:"서울어딘가",
        profile_iamge:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwTRkf2JdOw1pAZTMImAv3eEIQr0QDVGL_H0hzxiR3PiBk9SASjg",
        access:false
      }
    ],
    [
      {
        name:"나비",
        category:"자연",
        phone:"010-1234-4567",
        business_call:"02-1234-4567",
        business:"없음",
        email:"userid@gmail.com",
        address:"자연",
        profile_iamge:"http://zooa.kr/wp-content/uploads/2015/03/011.png",
        access:true
      },
      {
        name:"냐냥",
        category:"고양이",
        phone:"010-1234-4567",
        business_call:"02-1234-4567",
        business:"없음",
        email:"nyaa@gmail.com",
        address:"자연",
        profile_iamge:"https://tshop.r10s.jp/gold/free-stitch/good_img/FS-3801-7.jpg?fitin=128:128",
        access:true
      },
      {
        name:"호랑",
        category:"호랑이 아빠",
        phone:"010-1234-4567",
        business_call:"02-1234-4567",
        business:"ZOO작",
        email:"tiger@gmail.com",
        address:"동물원",
        profile_iamge:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Siberischer_tiger_de_edit02.jpg/220px-Siberischer_tiger_de_edit02.jpg",
        access:false
      },
      {
        name:"고라",
        category:"고라니 왕",
        phone:"010-1234-4567",
        business_call:"02-1234-4567",
        business:"ZOO작",
        email:"GORANI@gmail.com",
        address:"산속",
        profile_iamge:"https://pbs.twimg.com/profile_images/579645712675127296/qWm_u02-_400x400.jpg",
        access:false
      }
    ]
  ]
}
}

export default function (state = initialState, action){
  switch(action.type){
    case types.CHANGE_ADD_FORM:
      return {
        ...state,
        add_form_clsname:action.add_form_clsname,
        add_form_status:action.add_form_status
      }
    default :
      return state;
  }
}
